### ISSUE TITLE
css style "position: fixed" do not let the component fixed in browser window

### ISSUE THREAD

**Issue by Gfast2** [chenglou/react-motion#441]
Hi Guys,

I just play with React Motion for a while & Find it really impressive! 👍 

But there is some issue here:
I animate (scroll) a parent div with <Motion />. One of its child is main-navi, so I'd like to let it stay fixed in window after scrolling animation. But old css stylesheet without React-Motion works not any more (add css style: "position:fixed" after animation) 
And I figured out the fixed position of it is its parent div (which is animated with <Motion />) but not browser window anymore.

Is there some work around on this?

**Comment by nkbt** [comment]
I feel like you have a problem with your CSS rather then with
react-collapse here. Not really possible to say more at the time unless you
have minimal reproducible case in codepen/jsbin
-- 
Nik Butenko
nik@butenko.me
http://github.com/nkbt

**Comment by Gfast2** [comment]
Hi nkbt, Thanks!
I'd try to make a codeopen demo later.
Right now the thing works like so:
If the value of key "scrollup" in redux store is -400, then add the css class `fixed`, if not, remove it. BTW, I'm using ["classNames"](https://github.com/JedWatson/classnames) to handle this.

This is the css classes that this component is using:

```css
/* Main Menu wrapper*/
.MainMenu-wrapper {
    height:50px;
    left:0px;
    background-color: #AEAEAE;
    margin: 0 auto;    
    text-align: left;
    position: absolute;
    width: 100%;    
    padding-left: 50px;
    z-index: 10;
}

.MainMenu-wrapper.fixed {
  top:0px;
  z-index: 2;
  position: fixed;
}
```
And these are functions in react component which are using it:
```javascript
  renderBtn() {
    const aClass = d => classNames({ // render button group focus according to redux store
      'buttonMain': true,
      'mainClicked': this.props.mainnavi === d ? true:false
    });

    return Object.keys(mm).map( (el) => 
      <button 
        className={aClass(mm[el].id)} 
        key={mm[el].id} 
        id={mm[el].id} 
        onClick = {this.handleClick}
      >
      {trans(mm[el].name)}
      </button>
    );
  }

  objRender() {
    return classNames({
      'MainMenu-wrapper': true,
      'fixed':this.props.scrollup === -400 ? true : false
    });
  }

  render() {
    return (
      <div className={this.objRender()}>
        {this.renderBtn()}
      </div>
    );
  }
```
I can see the css class "fixed" kicked in / out in Chrome on this component. And the `postion` of class `fixed` over write the same key in `MainMenu-wrapper'.
BTW, when I set `top` of class `fixed` to a certain value (unit Pixel here). I get always a offset from its parent element but not the whole screen.

It is complacated, I think. Hopefully, I can create a codeopen to recreate this effect.
