### ISSUE TITLE
Spring function breaks Safari

### ISSUE THREAD

**Issue by mikeynova** [chenglou/react-motion#477]
When I remove the spring function it behaves much better in safari. I was wondering if anyone was aware of this bug or if there is a similar function I can use that won't break one of the browsers. 

For reference this is the spring function in Safari:
![safari](https://user-images.githubusercontent.com/8882783/27548690-869ba3f8-5a4e-11e7-9825-0287c3992e58.gif)

And this is the Spring Function in Chrome:
![chrome](https://user-images.githubusercontent.com/8882783/27548719-9b874a4c-5a4e-11e7-9a48-78f4603c0f6c.gif)

**Comment by bloodyowl** [comment]
do you have lots of nested column flex elements?

**Comment by mikeynova** [comment]
No, and I’m not using flex either.

**Comment by bloodyowl** [comment]
that's weird. could you record the layout/rendering in safari devtools, seems like a recalc issue to me?

<img width="647" alt="screen shot 2017-06-26 at 19 55 51" src="https://user-images.githubusercontent.com/1688645/27552956-7d064a7c-5aa9-11e7-9041-a7a02a93375e.png">

**Comment by mikeynova** [comment]
![layoutsafari](https://user-images.githubusercontent.com/8882783/27554036-fb145a1e-5a61-11e7-8bc3-46e4665afad7.gif)

**Comment by bloodyowl** [comment]
yeah, composite seems like the culprit here. this is some CSS layout issue; not related to react-motion

**Comment by mikeynova** [comment]
Huh, then why does it work fine if I remove the spring function?

**Comment by bloodyowl** [comment]
what do you mean?

**Comment by mikeynova** [comment]
If I remove the spring function from react-motion it becomes much smoother, not ideal, but much smoother. 

![anotherexample](https://user-images.githubusercontent.com/8882783/27559976-5a562b64-5a77-11e7-9e5e-d5e458096108.gif)

**Comment by mikeynova** [comment]
```javascript
import React, { Component } from 'react'
import { Motion, spring } from 'react-motion'
import { Collapse } from 'react-collapse'
import { array, shape } from 'prop-types'

import DrawerContent from '../../components/drawer-content.jsx'

class RecentDrawer extends Component {
  constructor(props) {
    super(props)
    this.state = {
      isOpened: false,
      startMotion: 0, endMotion: 400,
      polyHeightStart: 200, polyHeightEnd: 200,
    }
    this.handleOpenDrawer = this.handleOpenDrawer.bind(this)
  }

  handleOpenDrawer() {
    if (this.state.isOpened === false) {
      document.getElementsByClassName('recent-drawer-opened')[0].classList.add('recent-visible')
      document.getElementsByClassName('recent-content-container')[0].classList.add('recent-opened')
      document.getElementsByClassName('recent-drawer-container')[0].classList.add('recent-height')
      this.setState({
        isOpened: true,
        startMotion: 400, endMotion: 4000,
        polyHeightStart: 200, polyHeightEnd: 90,
      })
    } else {
      document.getElementsByClassName('recent-drawer-opened')[0].classList.remove('recent-visible')
      document.getElementsByClassName('recent-content-container')[0].classList.remove('recent-opened')
      document.getElementsByClassName('recent-drawer-container')[0].classList.remove('recent-height')
      this.setState({
        isOpened: false,
        startMotion: 4000, endMotion: 400,
        polyHeightStart: 90, polyHeightEnd: 200,
      })
    }
  }

  render() {
    const { isOpened } = this.state
    const mainButtonRotation =
      isOpened ? { rotate: spring(-270, { stiffness: 700, damping: 30 }) } : { rotate: spring(0, { stiffness: 700, damping: 30 }) }
    return (
      <div className="recent-drawer-container">
        <div className="recent-polygon-container" >
          <Motion defaultStyle={{ a: this.state.startMotion, b: this.state.polyHeightStart }} style={{ a: spring(this.state.endMotion), b: spring(this.state.polyHeightEnd) }}>
            {interpolatingStyle =>
              (<div className="recent-button-container" style={{ width: interpolatingStyle.a, height: interpolatingStyle.b }}>
                <div className="recent-polygon">
                  <h1 className="recent-button">RECENT</h1>
                  <Motion style={mainButtonRotation}>
                    {({ rotate }) =>
                      (<i className="fa fa-chevron-right fa-2x" style={{ transform: `rotate(${rotate}deg)` }} onClick={this.handleOpenDrawer} aria-hidden="true"/>)}
                  </Motion>
                </div>
              </div>)}
          </Motion>
        </div>
        <div className="recent-content-container">
          <DrawerContent preview={this.props.videos.preview} allVideos={this.props.videos.allVideos}/>
          <Collapse className="recent-drawer-opened" isOpened={this.state.isOpened}>
            <DrawerContent preview={this.props.videos.preview} allVideos={this.props.videos.allVideos}/>
          </Collapse>
        </div>
      </div>
    )
  }
}

RecentDrawer.propTypes = {
  videos: shape({
    preview: array.isRequired,
    allVideos: array.isRequired,
  }).isRequired,
}

export default RecentDrawer
```

**Comment by mikeynova** [comment]
My css as well, just to throw it all out there

```css
.recent-drawer-container {
  background: white;
  width: 100%;
  position: relative;
  height: 200px;
  -webkit-touch-callout: none; /* iOS Safari */
  -webkit-user-select: none; /* Safari */
  -khtml-user-select: none; /* Konqueror HTML */
  -moz-user-select: none; /* Firefox */
  -ms-user-select: none; /* Internet Explorer/Edge */
  user-select: none;
  -webkit-box-shadow:0px 2px 1px #888888;
  -moz-box-shadow:0px 2px 1px #888888;
  box-shadow:0px 2px 1px #888888;
  overflow: hidden;

  &.recent-height {
    height: 100%;
  }

  .recent-polygon-container {
    position: relative;
    float: left;
    z-index: 1;

    .recent-button-container {
      filter: drop-shadow(0 5px 10px #888888);

      .recent-polygon {
        background: #F2F0F3;
        height: 100%;
        width: 85%;
        -webkit-clip-path: polygon(0 0, 100% 0, 57% 100%, 0 100%); /* For Safari 5.1 to 6.0 */
        clip-path: polygon(0 0, 100% 0, 57% 100%, 0 100%);

        .recent-button {
          position: absolute;
          margin: {
            left: 30px;
            top: 30px;
          };
          background: -webkit-linear-gradient(left, #AEAEAE, #787777); /* For Safari 5.1 to 6.0 */
          background: -o-linear-gradient(right, #AEAEAE, #787777); /* For Opera 11.1 to 12.0 */
          background: -moz-linear-gradient(right, #AEAEAE, #787777); /* For Firefox 3.6 to 15 */
          background: linear-gradient(to right, #AEAEAE, #787777);
          color: transparent;
          -webkit-background-clip: text;
          background-clip: text;
        }

        .fa.fa-chevron-right {
          margin: {
            left: 155px;
            top: 34px;
          };
          cursor: pointer;
          background: -webkit-linear-gradient(left, #A24E77, #E06C90); /* For Safari 5.1 to 6.0 */
          background: -o-linear-gradient(right, #A24E77, #E06C90); /* For Opera 11.1 to 12.0 */
          background: -moz-linear-gradient(right, #A24E77, #E06C90); /* For Firefox 3.6 to 15 */
          background: linear-gradient(to right, #A24E77, #E06C90);
          color: transparent;
          -webkit-background-clip: text;
          background-clip: text;
        }
      }
    }
  }

  .recent-content-container {
    position: relative;
    z-index: 0;
    margin: auto;

     &.recent-opened {
      left: 56.5%;
      transform: translate(-50%, -50%);
      -webkit-transform: translate(-50%, -50%);
      top: 50%;
    }

    .recent-visible {
      overflow: visible !important;
    }
  }
}
```
